    ---
title: "Titanic Data"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggthemes)

``` 

```{r}
df <- read.csv("./datasets/titanic.csv", stringsAsFactors = FALSE)

df <- as_tibble(df)
df
# convert col to factors (categories)
df$Survived <- as.factor(df$Survived)
df$Pclass <- as.factor(df$Pclass)
df$Sex <- as.factor(df$Sex)
df$Embarked <- as.factor(df$Embarked)
df
``` 

```{r}
hist <- ggplot(data = df, aes(x = Age))
hist + geom_histogram(binwidth = 5, color = "darkslategray",
                      fill = "darkslategray4", alpha = 0.5) +
       ggtitle("Age Distribution on the Titanic") + 
       labs(y = "Number of Passengers", x = "Age") +
       theme_minimal()
``` 

```{r}
employee.data <- read.csv("./datasets/employee_data.csv",
                          skip = 23, stringsAsFactors = FALSE) 
employee.data <- as_tibble(employee.data)
employee.data$gender <- as.factor(employee.data$gender)
employee.data$title <- as.factor(employee.data$title)

emp.a <- filter(employee.data, salary > 45000)
head(emp.a, 1)
dim(emp.a)
hist <- ggplot(data = emp.a, aes(x = salary))
hist + geom_histogram(binwidth = 5000, color = "darkslategray", 
fill = "darkslategray4", alpha = 0.7) +
labs(title = "Salary distribution in the employee data", y = "Number of employees in the salary bracket", x = "Salary") +
theme_solarized(light = FALSE, base_size = 15, base_family = "serif")
```
