---
title: "Excercise 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r exercise1}
x <- c(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)
y <- x + 2
z <- y * 3
answer <- (z - 6) / 3
print(answer)
```

```{r exercise2}
employee_name <- c("Belinda Johnes", "Maria Delar", "Math Smith",
                   "Matt Williams", "Robert Mathews", "Julia Walters",
                   "Andrea Cheng", "July Horitz", "Danielle Muller",
                   "Esteban Lugo")
typeof(employee_name)

salary <- c(3000, NA, NA, NA, NA, 4000, 3000, 5000, 1000, 5000)
typeof(salary)

employees <- c(employee_name, salary)
typeof(employees)
```

```{r execise3}
yearly_bonus <- c(TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)
employees <- c(employees, yearly_bonus)
employees
typeof(employees)

coerce.check <- c(salary, yearly_bonus)

coerce.check
```

```{r exercise4}
years_of_experience <- c(8, 10, 10, 1, 10, 10, 8, 12, 1, 12)
sum(years_of_experience)
mean(years_of_experience)
median(years_of_experience)
length(years_of_experience)
sd(years_of_experience)
round(sd(years_of_experience))
print(round(sd(years_of_experience)))
```


```{r exercise5}
# Find out what arguments are needed:
args(sample)
args(median)

median(years_of_experience, na.rm = TRUE)
median(salary)
median(salary, na.rm = TRUE)
```

```{r exercise6}
# write a function that flips coin 100 times
flip <- function() {
  coin <- c("heads", "tails")
  toss <- sample(coin, 100, replace = TRUE, prob = c(0.3, 0.7))
  return(toss)
}

flip()
```

