---
title: "Section 7"
output: html_document
---

```{r setup include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
year <- c(2, 3, 4, 5, 8, 9, 8)
size <- c("medium", "small", "medium", "small", "small", "medium",
          "extra large")
mpg <- c(25, 47, 27, 36, 31, 2, 36)
geerbox <- c("manual", "manual", "auto", "auto", "manual", "manual", "auto")
name <- c("VolkswagenTouareg", "CitroenC3", "AudiA3", "ToyotaYaris",
           "KiaForte", "DaciaLogan", "NisanPajero")

df_cars <- data.frame(row.names = name, "Year" = year, "Size" = size,
                     "MPG" = mpg, "Geerbox" = geerbox)
df_cars
```

```{r}
working.dir <- getwd()

setwd <- working.dir
```
```{r importTable}
my.pok <- read.table("./datasets/pokRdex_comma.csv",
                      sep = ',', 
                      header = TRUE, 
                      stringsAsFactors = FALSE)
                    
# my.pok 
```

```{r exercise17}
# Read csv file
df_employees <- read.csv("./datasets/employee_data.csv",
                          skip = 23,
                          nrows = 200,
                          stringsAsFactors = FALSE)
# head(df_employees, 5)

# Rename variables
names(df_employees) <- c("Employee number", "First name",
                        "Last name", "Birth date", 
                        "Gender", "Job title", "Salary",
                        "From date", "To date")

head(df_employees, 5)

write.csv(df_employees, file = "./datasets/employee_exercise.csv",
          row.names = FALSE)
```

```{r}
df_cars[["PassdAnualInspection"]]
df_cars
```

```{r}
library('ggplot2')
```